language: cpp

script:
  - make CXX=clang++-5.0 source
  - make clean
  - make CXX=g++-7
  - bash <(curl -s https://codecov.io/bash)
  - cppcheck --enable=all .

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang++-5.0
            - g++-7
            - cppcheck
