dist: trusty
sudo: false
language: c++

addons:
  apt:
    update: true
    sources: ubuntu-toolchain-r-test
    packages: g++-6

script:
  - make TMP_DIR=tmp CXX=g++-6 EXTRA=--coverage
  - bash <(curl -s https://codecov.io/bash)
  - cat index.html

before_deploy: rm -f .gitignore

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master
