dist: trusty
sudo: false
language: c++

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: g++-6

script:
  - make CXX=g++-6 EXTRA=--coverage source
  - bash <(curl -s https://codecov.io/bash)
