language: cpp
dist: trusty
sudo: false

addons:
  apt:
    update: true
    sources: ubuntu-toolchain-r-test
    packages:
      - g++-6
      - cppcheck

script:
  - make TMP_DIR=tmp CXX=g++-6 EXTRA=--coverage
  - bash <(curl -s https://codecov.io/bash)
  - make lint

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master
