before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  - sudo apt-get -y install g++-6

language: c++

script:
  make CXX=g++-6 EXTRA=--coverage source
  bash <(curl -s https://codecov.io/bash)
